### PR TITLE
Create NXCheats

### PR DESCRIPTION
**Pull request by klw9326**

### CODE REVIEW

**Comment by Krutonium** [comment]
This seems to be an empty commit?

**Comment by Deepak8800** [comment]
can you make a inf.wpn durability cheat for zelda totk v 1.1.1

**Comment by VoltageMiner** [comment]
What's the point of this? Did you make a mistake or something?

**Comment by YuriYuri0-0** [comment]
> What's the point of this? Did you make a mistake or something?

no but i thought wpn durability should be there in the cheat

**Comment by YuriYuri0-0** [comment]
thanks for the cheats

**Comment by bad1dea** [comment]
Closing -- not sure what this is.

**Pull request closed without merging**
